### ISSUE TITLE
Feature: add usage/metrics to an instance of anx-api

### ISSUE THREAD

**Issue by joelgriffith** [appnexus/anx-api#40]
As a consumer of anx-api, it'd be a nice feature for it to keep a hold of requests that it's made, and return an object of statistics:

```
anxApiInstance.getUsageStatistics();
// Outputs:
{
  total_calls: 2,
  failed_calls: 1,
  successful_calls: 1,
  calls: [{
    url: 'http://api.appnexus.com/advertiser?id=123',
    response: 401,
    response_time_ms: 235
  }, {
    url: 'http://api.appnexus.com/line-item',
    response: 200,
    response_time_ms: 539
  }]
}
```

I'm open to changing this up a bit, would be a nice feature for clients that do data aggregation.

**Comment by tsantef** [comment]
For "calls" should it filter out querystring differences? Also should the request methods be seperated out and tracked?

**Comment by tsantef** [comment]
Also should it be an opt-in feature through the constructor options?

**Comment by joelgriffith** [comment]
Yeah, those are good questions, and the more I think of it it's probably better left to implement in userland as there's just too much info that can be captured, and every client will likely want something totally different than the other(s)
