### ISSUE TITLE
Cors error when using anx-api with vuejs

### ISSUE THREAD

**Issue by ghost** [appnexus/anx-api#81]
Hello,

I'm trying to use your wrapper for a project who using vuejs,
and i'm blocked due to the cors rules, after trying to change headers in webpack and in params of the request i'm still not able to get the data, did you already face this issue ?

I have tryied with Axios only too and the result is the same, so I think the error is coming from here

```
Failed to load https://api.appnexus.com/auth: 
Response to preflight request doesn't pass access control check: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost.com:8000' is therefore not allowed access.
```

```
errors.js?9b1e:9 Uncaught (in promise) ApiError
    at Object.exports.buildError (webpack-internal:///./node_modules/anx-api/lib/errors.js:224:12)
    at _self._config.request.then.catch (webpack-internal:///./node_modules/anx-api/lib/api.js:136:34)
```

Thanks !

**Comment by tsantef** [comment]
I will give this a try on Monday, ooo till then. @danvanhorn if your able to take a look at this before hand that would be great.

**Comment by tsantef** [comment]
@ziitrus as a side question what domain will this code eventually be served from in production. We may need to add it to our allowed domains list.

**Comment by ghost** [comment]
@tsantef Hello, 

I have tried with fetch too, just to eliminated the axios part, it's working but getting a Opaque response, blocked by CORB rules. Actually the only solution during the development part is to proxying into webpack.

For your second point, is it possible to get an other canal to discuss about it ?

**Comment by tsantef** [comment]
I was a able to duplicate this issue and it is due to our server side cors configuration. In order to login via a browser you will need to either create a server side proxy that forwards browser requests or request your site be added to AppNexus's cors rules.
